# Generated by Django 3.0.2 on 2020-03-31 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recentitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentitems',
            name='user',
        ),
    ]
